# Site Settings
title: Data Science Portfolio
description: Exploring the frontiers of AI and Machine Learning
baseurl: ""
url: "https://yourusername.github.io"

# Theme Settings
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme

# SEO Settings
author:
  name: Robson Lopes Jr
  email: your.email@example.com
twitter:
  username: yourtwitterhandle
  card: summary_large_image
social:
  name: Robson Lopes Jr
  links:
    - https://twitter.com/yourtwitterhandle
    - https://www.linkedin.com/in/robsonlopesjr
    - https://github.com/robsonlopesjr

# Analytics
google_analytics: UA-XXXXXXXX-X

# Build Settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Custom Settings
show_downloads: true
logo: /assets/img/logo.png

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/

# Default Settings
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Robson Lopes Jr"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
      author: "Robson Lopes Jr"

# Exclude Files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github
  - README.md
  - LICENSE
  - CNAME
