# Site Settings
title: "Marcos Lino | Data Science & AI Portfolio"
tagline: "Transformando o futuro através dos dados"
description: >-
  Cientista de Dados e Especialista em IA, unindo biologia e tecnologia
  para criar soluções inovadoras que impactam o mundo.
url: "https://marcosflino.github.io"
baseurl: ""
repository: "marcosflino/marcosflino.github.io"

# Theme Configuration
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
color-scheme: dark

# SEO and Analytics
google_analytics: "UA-XXXXXXXX-X"
author:
  name: "Marcos Lino"
  bio: "Cientista de Dados | Especialista em IA"
  location: "Portugal"
  email: "seu.email@gmail.com"
  github: "marcosflino"
  linkedin: "marcosfl"
  kaggle: "marcosflino"
  medium: "@marcosflino"

# Build Settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
future: true

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/
  publications:
    output: true
    permalink: /publications/:path/
  talks:
    output: true
    permalink: /talks/:path/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
  - jekyll-github-metadata
  - jekyll-mentions
  - jekyll-redirect-from

# Asset Pipeline
sass:
  sass_dir: _sass
  style: compressed

# Custom Settings
animated_header: true
enable_dark_mode: true
show_downloads: true
logo_path: /assets/img/profile.png

# Social Media Settings
social_links:
  github: "marcosflino"
  linkedin: "marcosfl"
  kaggle: "marcosflino"
  medium: "@marcosflino"

# Performance Optimization
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: []
