# Site Settings
title: "Marcos Lino | Data Science & AI Portfolio"
description: "Cientista de Dados e Especialista em IA com background em Biologia"
baseurl: "/portfolio"
url: "https://marcosflino.github.io"

# Theme Configuration
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0

# SEO & Social
author:
  name: "Marcos Lino"
  bio: "Data Scientist & AI Specialist"
  location: "Brazil"
  email: "seu.email@exemplo.com"
social:
  github: marcosflino
  linkedin: marcosflino
  researchgate: profile/seu-perfil

# Plugin Configuration
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme
  - jekyll-github-metadata

# Content Structure
collections:
  projects:
    output: true
    permalink: /projects/:path/
  publications:
    output: true
    permalink: /publications/:path/
  blog:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Layout Defaults
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
      show_sidebar: true
      show_metrics: true
  - scope:
      path: ""
      type: "publications"
    values:
      layout: "publication"
      show_citations: true
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      show_date: true

# Visual Configuration
logo: /assets/img/profile.jpg
show_downloads: false
google_analytics: UA-XXXXXXXX-X

# Custom Navigation
navigation:
  - title: "Sobre"
    url: "/about/"
  - title: "Projetos"
    url: "/projects/"
  - title: "Publicações"
    url: "/publications/"
  - title: "Blog"
    url: "/blog/"
  - title: "Contato"
    url: "/contact/"

# Theme Colors
colors:
  primary: "#0077B5"      # Professional Blue
  secondary: "#333333"    # Dark Gray
  accent: "#00A0DC"       # Light Blue
  background: "#FFFFFF"   # White
  text: "#2C3E50"        # Dark Blue-Gray

# Performance Optimization
sass:
  style: compressed
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  input: GFM

# Build Settings
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - README.md
  - CHANGELOG.md
