title: "Marcos Lino | Data Science & AI Portfolio"
tagline: "Transformando dados em decisões inteligentes"
description: >-
  Especialista em Ciência de Dados e Inteligência Artificial, 
  combinando conhecimentos em Biologia com tecnologia de ponta 
  para criar soluções inovadoras.
url: "https://marcosflino.github.io"
baseurl: ""
locale: "pt_BR"
version: "2.0"

theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
color-scheme: dark

markdown: kramdown
highlighter: rouge
permalink: /:title/
future: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

sass:
  sass_dir: _sass
  style: compressed

collections:
  projects:
    output: true
    permalink: /projects/:path/
  publications:
    output: true
    permalink: /publications/:path/

defaults:
  - scope:
      path

