theme: jekyll-theme-minimal
title: Marcos Lino - Portfólio de Ciência de Dados e IA
description: Bem-vindo ao meu portfólio! Aqui você encontrará projetos, artigos e informações sobre meu trabalho em Ciência de Dados e Inteligência Artificial.
show_downloads: false
google_analytics:
github:
  is_project_page: true
