title: "Marcos Lino | Data Science & AI Portfolio"
tagline: "Transformando dados em decisões inteligentes"
description: >-
  Especialista em Ciência de Dados e Inteligência Artificial, 
  combinando conhecimentos em Biologia com tecnologia de ponta 
  para criar soluções inovadoras.
url: "https://marcosflino.github.io"
baseurl: ""
locale: "pt_BR"
version: "2.0"

theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
color-scheme: dark

markdown: kramdown
highlighter: rouge
permalink: /:title/
future: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-github-metadata
  - jekyll-relative-links
  - jemoji

sass:
  sass_dir: _sass
  style: compressed

collections:
  projects:
    output: true
    permalink: /projects/:path/
  publications:
    output: true
    permalink: /publications/:path/

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      author: "Marcos Lino"
  - scope:
      path: "_projects"
    values:
      layout: "project"
  - scope:
      path: "_publications"
    values:
      layout: "publication"

social_links:
  github: marcosflino
  linkedin: marcosfl
  kaggle: marcosflino
  medium: marcosflino
  email: seu.email@gmail.com

google_analytics: "UA-XXXXXXXX-X"
google_site_verification: "verification_code"

twitter:
  username: marcosflino
  card: summary_large_image
facebook:
  app_id: 123456789
  publisher: 123456789
social:
  name: Marcos Lino
  links:
    - https://twitter.com/marcosflino
    - https://www.linkedin.com/in/marcosfl
    - https://github.com/marcosflino

features:
  projects:
    enabled: true
    show_count: 6
  publications:
    enabled: true
    show_count: 4
  blog:
    enabled: true
    show_count: 5

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: []

webmaster_verifications:
  google: ""
  bing: ""
  alexa: ""
  yandex: ""

author:
  name: Marcos Lino
  bio: >-
    Data Scientist & AI Specialist com background em Biologia,
    especializado em machine learning e análise de dados genômicos.
  avatar: /assets/images/profile.jpg
  location: "Porto, Portugal"
  company: "Your Company"
  company_url: "https://company.com"
