title: "Marcos Lino - Cientista de Dados"
description: "Portfólio de projetos e habilidades em Ciência de Dados e Inteligência Artificial."
theme: jekyll-theme-minimal

# Social links
social:
  - name: LinkedIn
    url: https://www.linkedin.com/in/marcosfl/
  - name: GitHub
    url: https://github.com/marcosflino
  - name: Kaggle
    url: https://kaggle.com/marcosflino
  - name: Medium
    url: https://medium.com/marcosflino

# Exibir estatísticas do GitHub
github_stats: true

# Exibir ícones de habilidades
skills_icons: true
